services:
  - type: web
    name: planner-api
    env: python
    buildCommand: chmod +x backend/build.sh && ./backend/build.sh
    startCommand: cd backend && gunicorn --bind 0.0.0.0:$PORT simple_main:app
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: BOT_TOKEN
        sync: false
    autoDeploy: true

  - type: web
    name: planner-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://planner-api.onrender.com
    autoDeploy: true 
